############################################################
# +------------------------------------------------------+ #
# |     Plugin configuration file for SortInventory      | #
# |                                                      | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################
Sort: 

############################################################
# +------------------------------------------------------+ #
# |                        General                       | #
# +------------------------------------------------------+ #
############################################################
Library:
    # Set Language. Currently supported: EN
    Language: EN

    # Set the key to activate sort. 
    # Deactivate the HOTKEY by setting SortKey: KEY_DEACTIVE
    SortKey: KEY_S

    # This is the sorting sequence
    SortSEQ: WOOD_SWORD,IRON_SWORD,GOLD_SWORD,DIAMOND_SWORD,WOOD_AXE,IRON_AXE,GOLD_AXE,DIAMOND_AXE,WOOD_SPADE,IRON_SPADE,GOLD_SPADE,EGG,STONE,DIRT,WOOD,IRON_INGOT,FLINT,WOOL


############################################################
# +------------------------------------------------------+ #
# |                  Properties for Debug                | #
# +------------------------------------------------------+ #
############################################################
Debug:
    Permissions: false
    Inventory: false
    OnEnable: false
    Keyboard: false
