############################################################
# +------------------------------------------------------+ #
# |     Plugin configuration file for SortInventory      | #
# |                                                      | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################

############################################################
# +------------------------------------------------------+ #
# |                        General                       | #
# +------------------------------------------------------+ #
############################################################
General:
    # Set Language. Currently supported: EN
    Language: EN

############################################################
# +------------------------------------------------------+ #
# |             Properties for Sort Command              | #
# +------------------------------------------------------+ #
############################################################
Sort: 
    # Set the key to activate sort. 
    # Deactivate the HOTKEY by setting SortKey: KEY_DEACTIVE
    SortKey: KEY_S
    SortSeq: [1, 2, 3, 4, 5]

############################################################
# +------------------------------------------------------+ #
# |                  Properties for Debug                | #
# +------------------------------------------------------+ #
############################################################
Debug:
    Permissions: false
    SortInventory: false
    OnEnable: false
    Keyboard: false
